# FIXME: some day find out why FIND_LIBRARY does not pop for Shlwapi on MSVC..

IF (WIN32)
  SET(SHLWAPI_LIBRARY shlwapi)
ELSE ()
  FIND_LIBRARY(SHLWAPI_LIBRARY NAMES Shlwapi)
ENDIF ()

SET(SHLWAPI_LIBRARIES ${SHLWAPI_LIBRARY})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Shlwapi DEFAULT_MSG SHLWAPI_LIBRARY SHLWAPI_LIBRARIES)

MARK_AS_ADVANCED(SHLWAPI_LIBRARY SHLWAPI_LIBRARIES)
