# NS_VARNAME : generated header will define variable with this name
# NS_IN : input filename absolute
# NS_OUT : output filename absolute

FILE(READ ${NS_IN} HEXSTR HEX)

SET(OUT "")
STRING(APPEND OUT "/* generated by GenHeader.cmake - do not edit */\n")
STRING(APPEND OUT "unsigned char ${NS_VARNAME}[] = {")

STRING(LENGTH "${HEXSTR}" HEXLEN)
MATH(EXPR HEXLEN_MINUS2 "${HEXLEN} - 2")

IF(NOT (${HEXLEN_MINUS2} GREATER 0))
	# dummy default data
	STRING(APPEND OUT "0x00,")
ELSE()
	FOREACH(VV RANGE 0 ${HEXLEN_MINUS2} 2)
		STRING(SUBSTRING ${HEXSTR} ${VV} 2 HEXCHAR)
		STRING(APPEND OUT "0x${HEXCHAR},")
	ENDFOREACH()
ENDIF()

STRING(APPEND OUT "};")

FILE(WRITE ${NS_OUT} "${OUT}")
